CREATE DATABASE RISTORANTE;
USE RISTORANTE;


CREATE TABLE CLIENTE (
ID_CLIENTE INT AUTO_INCREMENT,
NOME VARCHAR(25),
COGNOME VARCHAR(25),
CONTATTO_PRINCIPALE VARCHAR(25),
ALLERGIE VARCHAR(30),
CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);


CREATE TABLE PRENOTAZIONE (
ID_PRENOTAZIONE INT AUTO_INCREMENT,
ID_CLIENTE INT,
DATA_PRENOTAZIONE DATE,
ORARIO_PRENOTAZIONE TIME,
NUM_PERSONE INT,
NUM_BAMBINI INT,
RICHIESTE_PARTICOLARI VARCHAR(50),
CONSTRAINT PK_PRENOTAZIONE PRIMARY KEY (ID_PRENOTAZIONE),
CONSTRAINT FK_CLIENTE_PRENOTAZIONE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);


CREATE TABLE DIPENDENTE (
ID_DIPENDENTE INT AUTO_INCREMENT,
NOME VARCHAR(50),
COGNOME VARCHAR(50),
CODICE_FISCALE VARCHAR(30),
RUOLO VARCHAR (30),
CONSTRAINT PK_DIPENDENTE PRIMARY KEY (ID_DIPENDENTE)
);


CREATE TABLE COMANDA (
ID_COMANDA INT AUTO_INCREMENT,
ID_CLIENTE INT,
ID_DIPENDENTE INT,
ID_TAVOLO INT,
ID_PRENOTAZIONE INT,
CONSTRAINT PK_COMANDA PRIMARY KEY (ID_COMANDA),
CONSTRAINT FK_DIPENDENTE_COMANDA FOREIGN KEY  (ID_DIPENDENTE) REFERENCES DIPENDENTE (ID_DIPENDENTE)
);


CREATE TABLE MENU (
ID_PIATTO INT AUTO_INCREMENT,
NOME_PIATTO VARCHAR(40),
CATEGORIA_PIATTO VARCHAR(40),
PREZZO DECIMAL(10,2),
COSTO DECIMAL(10,2),
ALLERGENI VARCHAR(40),
CONSTRAINT PK_MENU PRIMARY KEY (ID_PIATTO)
);


CREATE TABLE DETTAGLIO_COMANDA (
ID_DETTAGLIO_COMANDA INT AUTO_INCREMENT,
ID_COMANDA INT,
ID_PIATTO INT,
QUANTITA INT,
MODIFICHE VARCHAR(50),
CONSTRAINT PK_DETTAGLIO_COMANDA PRIMARY KEY (ID_DETTAGLIO_COMANDA),
CONSTRAINT FK_COMANDA_DETTAGLIO_COMANDA FOREIGN KEY (ID_COMANDA) REFERENCES COMANDA (ID_COMANDA),
CONSTRAINT FK_MENU_DETTAGLIO_COMANDA FOREIGN KEY (ID_PIATTO) REFERENCES MENU (ID_PIATTO)
);

SHOW TABLES;

DESCRIBE CLIENTE;
DESCRIBE PRENOTAZIONE;
DESCRIBE DIPENDENTE;
DESCRIBE COMANDA;
DESCRIBE MENU;
DESCRIBE DETTAGLIO_COMANDA;


-- POPOLAMENTO TABELLA CLIENTE 
INSERT INTO CLIENTE (NOME, COGNOME, CONTATTO_PRINCIPALE, ALLERGIE) VALUES 
('GAETANO', 'ROSSI', '+39 355 6668956', 'GLUTINE'),
('ANNA', 'CASILLI', '+39 358 2548971', 'LATTOSIO'),
('MARIO', 'ROSSI', '+39 333 8564369', 'NESSUNA'),
('GIUSEPPE', 'BIANCHI', '+39 255 7895621', 'FRUTTA SECCA');


-- POPOLAMENTO TABELLA PRENOTAZIONE 
INSERT INTO PRENOTAZIONE (ID_CLIENTE, DATA_PRENOTAZIONE, ORARIO_PRENOTAZIONE, NUM_PERSONE, NUM_BAMBINI, RICHIESTE_PARTICOLARI) VALUES 
(1, '2025-06-07' , '19:30', 4, 2, 'NESSUNA'),
(2, '2025-06-07', '20:00', 5, 3, 'COMPLEANNO'),
(3, '2025-06-10', '20:30', 2, 0, 'COMPLEANNO'),
(4, '2025-06-14', '21:30', 8, 3, 'TAVOLO ESTERNO'),
(1, '2025-06-07', '20:00', 2, 0, 'LUME DI CANDELA');


-- POPOLAMENTO TABELLA DIPENDENTE 
INSERT INTO DIPENDENTE (NOME, COGNOME, CODICE_FISCALE, RUOLO) VALUES
(LUCIANO, VERDI, VRDLCN92T45F205X, 'PRIMO CAMERIERE'),
(MARIO, ROSSI, RSSMRA85M12H501Z, 'CAMERIERE'),
(GIOVANNI, BONCI, BNCLGI77R22L219W, 'COMMIS SALA');


-- POPOLAMENTO TABELLA COMANDA
INSERT INTO COMANDA (ID_CLIENTE, ID_DIPENDENTE, ID_TAVOLO, ID_PRENOTAZIONE) VALUES 
(1, 2, 1, 1),
(2, 1, 2, 2),
(3, 3, 3, 3),
(4, 1, 4, 4),
(1, 2, 1, 5);


-- POPOLAMENTO TABELLA MENU
INSERT INTO MENU (ID_PIATTO, NOME_PIATTO, CATEGORIA_PIATTO, PREZZO, COSTO, ALLERGENI) VALUES 
(1, 'Spaghetti alla Carbonara', 'Primo', 12.50, 5.00, 'UOVA, LATTOSIO'),
(2, 'Risotto ai Funghi', 'Primo', 13.00, 5.50, 'LATTOSIO'),
(3, 'Filetto di Salmone', 'Secondo', 17.00, 9.00, 'PESCE'),
(4, 'Tiramisù', 'Dolce', 6.50, 3.00, 'UOVA, LATTOSIO, GLUTINE');


-- POPOLAMENOT TABELLA DETTAGLIO_COMANDA
INSERT INTO DETTAGLIO_COMANDA (ID_COMANDA, ID_PIATTO, QUANTITA, MODIFICHE) VALUES 
(1, 1, 2, 'NO GUANCIALE'),
(2, 2, 3, 'NO BURRO'),
(3, 3, 2, 'NO SALE'),
(4, 4, 4, 'GLUTINE'),
(5, 1, 2, 'NESSUNA');

SELECT * FROM CLIENTE;
SELECT * FROM PRENOTAZIONE;
SELECT * FROM DIPENDENTE;
SELECT * FROM COMANDA;
SELECT * FROM MENU;
SELECT * FROM DETTAGLIO_COMANDA;


SELECT 
P.*,C.NOME, C.COGNOME
FROM CLIENTE AS C 
JOIN PRENOTAZIONE AS P 
ON C.ID_CLIENTE=P.ID_CLIENTE; 

